services:
  - type: web
    name: organists-schedule-api
    env: docker
    dockerfilePath: ./Dockerfile

  - type: worker
    name: organists-schedule-migrate
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: dotnet ef database update --project OrganistsSchedule.WebApi/OrganistsSchedule.WebApi.csproj
